// Generated by scripts/generate-remotion-voiceover.mjs. Do not edit by hand.
export const FPS = 30;
export const SCENES = [
  {
    "id": "hero",
    "startFrame": 0,
    "durationFrames": 365
  },
  {
    "id": "intro",
    "startFrame": 365,
    "durationFrames": 413
  },
  {
    "id": "problem",
    "startFrame": 778,
    "durationFrames": 489
  },
  {
    "id": "passes",
    "startFrame": 1267,
    "durationFrames": 338
  },
  {
    "id": "refresh",
    "startFrame": 1605,
    "durationFrames": 459
  },
  {
    "id": "search",
    "startFrame": 2064,
    "durationFrames": 546
  },
  {
    "id": "ai",
    "startFrame": 2610,
    "durationFrames": 525
  },
  {
    "id": "cost",
    "startFrame": 3135,
    "durationFrames": 537
  },
  {
    "id": "work",
    "startFrame": 3672,
    "durationFrames": 333
  },
  {
    "id": "retainer",
    "startFrame": 4005,
    "durationFrames": 397
  },
  {
    "id": "cta",
    "startFrame": 4402,
    "durationFrames": 261
  }
] as const;
export const LINES = [
  {
    "id": "01-hero-01-female",
    "scene": 0,
    "speaker": "female",
    "text": "A website refresh does not have to mean starting over.",
    "file": "voiceover/01-hero-01-female.mp3",
    "startFrame": 16,
    "durationFrames": 93
  },
  {
    "id": "01-hero-02-male",
    "scene": 0,
    "speaker": "male",
    "text": "Right. The goal is a sharper web presence: better looking, easier to find, and less wasteful to run.",
    "file": "voiceover/01-hero-02-male.mp3",
    "startFrame": 117,
    "durationFrames": 212
  },
  {
    "id": "02-intro-01-male",
    "scene": 1,
    "speaker": "male",
    "text": "This starts with decades of software engineering judgment.",
    "file": "voiceover/02-intro-01-male.mp3",
    "startFrame": 381,
    "durationFrames": 100
  },
  {
    "id": "02-intro-02-female",
    "scene": 1,
    "speaker": "female",
    "text": "Yes, and that means looking past the surface: structure, maintainability, search signals, tool choices, and costs.",
    "file": "voiceover/02-intro-02-female.mp3",
    "startFrame": 489,
    "durationFrames": 253
  },
  {
    "id": "03-problem-01-female",
    "scene": 2,
    "speaker": "female",
    "text": "Most independent businesses have already put real work into their current website.",
    "file": "voiceover/03-problem-01-female.mp3",
    "startFrame": 794,
    "durationFrames": 132
  },
  {
    "id": "03-problem-02-male",
    "scene": 2,
    "speaker": "male",
    "text": "Exactly. But over time, the look can age, search signals can weaken, AI clarity can fade, and recurring costs can pile up quietly.",
    "file": "voiceover/03-problem-02-male.mp3",
    "startFrame": 934,
    "durationFrames": 297
  },
  {
    "id": "04-passes-01-male",
    "scene": 3,
    "speaker": "male",
    "text": "The work follows a practical checklist.",
    "file": "voiceover/04-passes-01-male.mp3",
    "startFrame": 1283,
    "durationFrames": 75
  },
  {
    "id": "04-passes-02-female",
    "scene": 3,
    "speaker": "female",
    "text": "Right: refresh the look, improve search, make the site AI-ready, and clean up unnecessary spend.",
    "file": "voiceover/04-passes-02-female.mp3",
    "startFrame": 1366,
    "durationFrames": 203
  },
  {
    "id": "05-refresh-01-female",
    "scene": 4,
    "speaker": "female",
    "text": "Instead of guessing from abstract design ideas, we compare real visual directions.",
    "file": "voiceover/05-refresh-01-female.mp3",
    "startFrame": 1621,
    "durationFrames": 151
  },
  {
    "id": "05-refresh-02-male",
    "scene": 4,
    "speaker": "male",
    "text": "Yes. Real options make the choice easier, preserve useful existing work, and give everyone a clear sign-off direction.",
    "file": "voiceover/05-refresh-02-male.mp3",
    "startFrame": 1780,
    "durationFrames": 248
  },
  {
    "id": "06-search-01-male",
    "scene": 5,
    "speaker": "male",
    "text": "Search Engine Optimization is precise. Search engines read visible content and behind-the-scenes details.",
    "file": "voiceover/06-search-01-male.mp3",
    "startFrame": 2080,
    "durationFrames": 221
  },
  {
    "id": "06-search-02-female",
    "scene": 5,
    "speaker": "female",
    "text": "Exactly: titles, headings, links, service wording, locations, and image labels each help the site explain itself clearly.",
    "file": "voiceover/06-search-02-female.mp3",
    "startFrame": 2309,
    "durationFrames": 265
  },
  {
    "id": "07-ai-01-female",
    "scene": 6,
    "speaker": "female",
    "text": "Today, many searches begin in chat boxes and AI assistants, not only search engines.",
    "file": "voiceover/07-ai-01-female.mp3",
    "startFrame": 2626,
    "durationFrames": 178
  },
  {
    "id": "07-ai-02-male",
    "scene": 6,
    "speaker": "male",
    "text": "Right. AI systems look for clear facts: who you are, what you do, where you work, which services matter, and what answer you provide.",
    "file": "voiceover/07-ai-02-male.mp3",
    "startFrame": 2812,
    "durationFrames": 287
  },
  {
    "id": "08-cost-01-male",
    "scene": 7,
    "speaker": "male",
    "text": "Then there are the small bills: domains, hosting, plugins, email add-ons, booking tools, analytics, and image tools.",
    "file": "voiceover/08-cost-01-male.mp3",
    "startFrame": 3151,
    "durationFrames": 277
  },
  {
    "id": "08-cost-02-female",
    "scene": 7,
    "speaker": "female",
    "text": "Yes. Some are essential. Some overlap. Some renew because nobody has looked at them in years.",
    "file": "voiceover/08-cost-02-female.mp3",
    "startFrame": 3436,
    "durationFrames": 200
  },
  {
    "id": "09-work-01-female",
    "scene": 8,
    "speaker": "female",
    "text": "The process starts with a short intake conversation.",
    "file": "voiceover/09-work-01-female.mp3",
    "startFrame": 3688,
    "durationFrames": 91
  },
  {
    "id": "09-work-02-male",
    "scene": 8,
    "speaker": "male",
    "text": "Right. What is already working? What should be preserved? Where are visitors getting stuck?",
    "file": "voiceover/09-work-02-male.mp3",
    "startFrame": 3787,
    "durationFrames": 182
  },
  {
    "id": "10-retainer-01-male",
    "scene": 9,
    "speaker": "male",
    "text": "Work begins with a practical initial bundle, usually around ten hours.",
    "file": "voiceover/10-retainer-01-male.mp3",
    "startFrame": 4021,
    "durationFrames": 135
  },
  {
    "id": "10-retainer-02-female",
    "scene": 9,
    "speaker": "female",
    "text": "Exactly. Progress is tracked clearly, with notes on what changed and a warning when the budget reaches halfway.",
    "file": "voiceover/10-retainer-02-female.mp3",
    "startFrame": 4164,
    "durationFrames": 202
  },
  {
    "id": "11-cta-01-female",
    "scene": 10,
    "speaker": "female",
    "text": "Send the link.",
    "file": "voiceover/11-cta-01-female.mp3",
    "startFrame": 4418,
    "durationFrames": 26
  },
  {
    "id": "11-cta-02-male",
    "scene": 10,
    "speaker": "male",
    "text": "Yes. Get the first pass. A clearer site starts with knowing what is already there.",
    "file": "voiceover/11-cta-02-male.mp3",
    "startFrame": 4452,
    "durationFrames": 175
  }
] as const;
export const CUES = {
  "problemDated": 998,
  "problemSearch": 1030,
  "problemAi": 1092,
  "problemCosts": 1149,
  "refreshGuessing": 1641,
  "refreshPreserve": 1868,
  "refreshSignoff": 1975,
  "searchTitles": 2329,
  "searchHeadings": 2346,
  "searchServices": 2383,
  "searchImages": 2454,
  "aiWhoWhat": 2926,
  "aiServices": 2989,
  "aiFacts": 2870,
  "aiAnswers": 3047,
  "costDomains": 3227,
  "costHosting": 3249,
  "costPlugins": 3270,
  "costEmail": 3292,
  "costBooking": 3328,
  "costAnalytics": 3364,
  "costImages": 3399
} as const;
export const TOTAL_FRAMES = 4663;
