// Generated by scripts/generate-remotion-voiceover.mjs. Do not edit by hand.
export const FPS = 30;
export const SCENES = [
  {
    "id": "hero",
    "startFrame": 0,
    "durationFrames": 312
  },
  {
    "id": "intro",
    "startFrame": 312,
    "durationFrames": 349
  },
  {
    "id": "problem",
    "startFrame": 661,
    "durationFrames": 418
  },
  {
    "id": "passes",
    "startFrame": 1079,
    "durationFrames": 294
  },
  {
    "id": "refresh",
    "startFrame": 1373,
    "durationFrames": 383
  },
  {
    "id": "search",
    "startFrame": 1756,
    "durationFrames": 445
  },
  {
    "id": "ai",
    "startFrame": 2201,
    "durationFrames": 416
  },
  {
    "id": "cost",
    "startFrame": 2617,
    "durationFrames": 435
  },
  {
    "id": "work",
    "startFrame": 3052,
    "durationFrames": 294
  },
  {
    "id": "retainer",
    "startFrame": 3346,
    "durationFrames": 341
  },
  {
    "id": "cta",
    "startFrame": 3687,
    "durationFrames": 223
  }
] as const;
export const LINES = [
  {
    "id": "01-hero-01-female",
    "scene": 0,
    "speaker": "female",
    "text": "A website refresh does not have to mean starting over.",
    "file": "voiceover/01-hero-01-female.mp3",
    "startFrame": 16,
    "durationFrames": 81
  },
  {
    "id": "01-hero-02-male",
    "scene": 0,
    "speaker": "male",
    "text": "Right. The goal is a sharper web presence: better looking, easier to find, and less wasteful to run.",
    "file": "voiceover/01-hero-02-male.mp3",
    "startFrame": 105,
    "durationFrames": 171
  },
  {
    "id": "02-intro-01-male",
    "scene": 1,
    "speaker": "male",
    "text": "This starts with decades of software engineering judgment.",
    "file": "voiceover/02-intro-01-male.mp3",
    "startFrame": 328,
    "durationFrames": 90
  },
  {
    "id": "02-intro-02-female",
    "scene": 1,
    "speaker": "female",
    "text": "Yes, and that means looking past the surface: structure, maintainability, search signals, tool choices, and costs.",
    "file": "voiceover/02-intro-02-female.mp3",
    "startFrame": 426,
    "durationFrames": 199
  },
  {
    "id": "03-problem-01-female",
    "scene": 2,
    "speaker": "female",
    "text": "Most independent businesses have already put real work into their current website.",
    "file": "voiceover/03-problem-01-female.mp3",
    "startFrame": 677,
    "durationFrames": 124
  },
  {
    "id": "03-problem-02-male",
    "scene": 2,
    "speaker": "male",
    "text": "Exactly. But over time, the look can age, search signals can weaken, AI clarity can fade, and recurring costs can pile up quietly.",
    "file": "voiceover/03-problem-02-male.mp3",
    "startFrame": 809,
    "durationFrames": 234
  },
  {
    "id": "04-passes-01-male",
    "scene": 3,
    "speaker": "male",
    "text": "The work follows a practical checklist.",
    "file": "voiceover/04-passes-01-male.mp3",
    "startFrame": 1095,
    "durationFrames": 66
  },
  {
    "id": "04-passes-02-female",
    "scene": 3,
    "speaker": "female",
    "text": "Right: refresh the look, improve search, make the site AI-ready, and clean up unnecessary spend.",
    "file": "voiceover/04-passes-02-female.mp3",
    "startFrame": 1169,
    "durationFrames": 168
  },
  {
    "id": "05-refresh-01-female",
    "scene": 4,
    "speaker": "female",
    "text": "Instead of guessing from abstract design ideas, we compare real visual directions.",
    "file": "voiceover/05-refresh-01-female.mp3",
    "startFrame": 1389,
    "durationFrames": 133
  },
  {
    "id": "05-refresh-02-male",
    "scene": 4,
    "speaker": "male",
    "text": "Yes. Real options make the choice easier, preserve useful existing work, and give everyone a clear sign-off direction.",
    "file": "voiceover/05-refresh-02-male.mp3",
    "startFrame": 1530,
    "durationFrames": 190
  },
  {
    "id": "06-search-01-male",
    "scene": 5,
    "speaker": "male",
    "text": "Search Engine Optimization is precise. Search engines read visible content and behind-the-scenes details.",
    "file": "voiceover/06-search-01-male.mp3",
    "startFrame": 1772,
    "durationFrames": 170
  },
  {
    "id": "06-search-02-female",
    "scene": 5,
    "speaker": "female",
    "text": "Exactly: titles, headings, links, service wording, locations, and image labels each help the site explain itself clearly.",
    "file": "voiceover/06-search-02-female.mp3",
    "startFrame": 1950,
    "durationFrames": 215
  },
  {
    "id": "07-ai-01-female",
    "scene": 6,
    "speaker": "female",
    "text": "Today, many searches begin in chat boxes and AI assistants, not only search engines.",
    "file": "voiceover/07-ai-01-female.mp3",
    "startFrame": 2217,
    "durationFrames": 142
  },
  {
    "id": "07-ai-02-male",
    "scene": 6,
    "speaker": "male",
    "text": "Right. AI systems look for clear facts: who you are, what you do, where you work, which services matter, and what answer you provide.",
    "file": "voiceover/07-ai-02-male.mp3",
    "startFrame": 2367,
    "durationFrames": 214
  },
  {
    "id": "08-cost-01-male",
    "scene": 7,
    "speaker": "male",
    "text": "Then there are the small bills: domains, hosting, plugins, email add-ons, booking tools, analytics, and image tools.",
    "file": "voiceover/08-cost-01-male.mp3",
    "startFrame": 2633,
    "durationFrames": 214
  },
  {
    "id": "08-cost-02-female",
    "scene": 7,
    "speaker": "female",
    "text": "Yes. Some are essential. Some overlap. Some renew because nobody has looked at them in years.",
    "file": "voiceover/08-cost-02-female.mp3",
    "startFrame": 2855,
    "durationFrames": 161
  },
  {
    "id": "09-work-01-female",
    "scene": 8,
    "speaker": "female",
    "text": "The process starts with a short intake conversation.",
    "file": "voiceover/09-work-01-female.mp3",
    "startFrame": 3068,
    "durationFrames": 84
  },
  {
    "id": "09-work-02-male",
    "scene": 8,
    "speaker": "male",
    "text": "Right. What is already working? What should be preserved? Where are visitors getting stuck?",
    "file": "voiceover/09-work-02-male.mp3",
    "startFrame": 3160,
    "durationFrames": 150
  },
  {
    "id": "10-retainer-01-male",
    "scene": 9,
    "speaker": "male",
    "text": "Work begins with a practical initial bundle, usually around ten hours.",
    "file": "voiceover/10-retainer-01-male.mp3",
    "startFrame": 3362,
    "durationFrames": 115
  },
  {
    "id": "10-retainer-02-female",
    "scene": 9,
    "speaker": "female",
    "text": "Exactly. Progress is tracked clearly, with notes on what changed and a warning when the budget reaches halfway.",
    "file": "voiceover/10-retainer-02-female.mp3",
    "startFrame": 3485,
    "durationFrames": 166
  },
  {
    "id": "11-cta-01-female",
    "scene": 10,
    "speaker": "female",
    "text": "Send the link.",
    "file": "voiceover/11-cta-01-female.mp3",
    "startFrame": 3703,
    "durationFrames": 30
  },
  {
    "id": "11-cta-02-male",
    "scene": 10,
    "speaker": "male",
    "text": "Yes. Get the first pass. A clearer site starts with knowing what is already there.",
    "file": "voiceover/11-cta-02-male.mp3",
    "startFrame": 3741,
    "durationFrames": 133
  }
] as const;
export const CUES = {
  "problemDated": 859,
  "problemSearch": 885,
  "problemAi": 933,
  "problemCosts": 978,
  "refreshGuessing": 1407,
  "refreshPreserve": 1598,
  "refreshSignoff": 1680,
  "searchTitles": 1966,
  "searchHeadings": 1980,
  "searchServices": 2010,
  "searchImages": 2067,
  "aiWhoWhat": 2452,
  "aiServices": 2499,
  "aiFacts": 2410,
  "aiAnswers": 2542,
  "costDomains": 2692,
  "costHosting": 2709,
  "costPlugins": 2725,
  "costEmail": 2742,
  "costBooking": 2770,
  "costAnalytics": 2797,
  "costImages": 2825
} as const;
export const TOTAL_FRAMES = 3910;
