// Fictional recipes and prices; translations preserve ingredients and preparation.
const courses = ['antipasti','primi','secondi','dolci'];
const dishes = [
 {course:0,price:24,en:['Burrata & heirloom tomatoes','Creamy burrata with ripe heirloom tomatoes, fresh basil and extra-virgin olive oil. Served cool, with a delicate milky centre and a bright, gently sweet finish.'],fr:['Burrata et tomates anciennes','Burrata crémeuse, tomates anciennes mûres, basilic frais et huile d’olive vierge extra. Servie fraîche, elle associe un cœur délicatement lacté à une finale vive et légèrement sucrée.'],es:['Burrata y tomates de variedades antiguas','Burrata cremosa con tomates maduros de variedades antiguas, albahaca fresca y aceite de oliva virgen extra. Se sirve fresca, con un centro lácteo delicado y un final vivo y ligeramente dulce.']},
 {course:0,price:28,en:['Beef carpaccio, rocket & Parmesan','Finely sliced raw beef fillet, dressed with lemon and olive oil, finished with rocket and shaved Parmesan. Tender and savoury, with peppery leaves and clean citrus acidity.'],fr:['Carpaccio de bœuf, roquette et parmesan','Filet de bœuf cru finement tranché, assaisonné de citron et d’huile d’olive, avec roquette et copeaux de parmesan. Une texture tendre, des notes poivrées et une fraîche acidité citronnée.'],es:['Carpaccio de ternera, rúcula y parmesano','Solomillo de ternera crudo en láminas finas, aliñado con limón y aceite de oliva, con rúcula y lascas de parmesano. Tierno y sabroso, con notas picantes de rúcula y una limpia acidez cítrica.']},
 {course:1,price:38,image:'tagliatelle.jpg',en:['Tagliatelle with black truffle','Fresh egg pasta tossed in butter and Parmesan, finished with thin shavings of black truffle. Silky ribbons carry an earthy aroma and a rich, lingering savouriness.'],fr:['Tagliatelles à la truffe noire','Pâtes fraîches aux œufs liées au beurre et au parmesan, puis garnies de fines lamelles de truffe noire. Des rubans soyeux aux arômes de sous-bois et à la saveur longue et généreuse.'],es:['Tagliatelle con trufa negra','Pasta fresca al huevo ligada con mantequilla y parmesano, terminada con finas láminas de trufa negra. Cintas sedosas de aroma terroso y sabor intenso y persistente.']},
 {course:1,price:32,en:['Saffron risotto','Carnaroli rice slowly cooked in vegetable stock with saffron, then finished with butter and Parmesan. Fluid and creamy, with floral warmth and a gently toasted depth.'],fr:['Risotto au safran','Riz Carnaroli cuit lentement dans un bouillon de légumes au safran, puis lié au beurre et au parmesan. Souple et crémeux, avec des notes florales chaleureuses et une profondeur légèrement grillée.'],es:['Risotto al azafrán','Arroz Carnaroli cocinado lentamente en caldo de verduras con azafrán y ligado con mantequilla y parmesano. Fluido y cremoso, con calidez floral y un fondo suavemente tostado.']},
 {course:2,price:46,en:['Sea bass, lemon & asparagus','Sea bass fillet pan-seared on its skin, with green asparagus and a lemon-butter sauce. Crisp skin gives way to delicate flakes; citrus keeps the finish fresh and light.'],fr:['Bar, citron et asperges','Filet de bar saisi à la poêle côté peau, asperges vertes et sauce au beurre citronné. Sous la peau croustillante, une chair délicate ; le citron apporte une finale fraîche et légère.'],es:['Lubina, limón y espárragos','Filete de lubina marcado en sartén por el lado de la piel, con espárragos verdes y salsa de mantequilla al limón. Piel crujiente y carne delicada, con un final cítrico fresco y ligero.']},
 {course:2,price:52,en:['Beef fillet, Barolo & celeriac','Seared beef fillet with a reduced Barolo wine jus and smooth celeriac purée. Deeply savoury and rounded, balanced by the subtle sweetness of the root vegetable.'],fr:['Filet de bœuf, Barolo et céleri-rave','Filet de bœuf saisi, jus réduit au vin Barolo et purée lisse de céleri-rave. Des saveurs profondes et rondes, équilibrées par la douceur subtile du légume.'],es:['Solomillo de ternera, Barolo y apionabo','Solomillo de ternera sellado, con jugo reducido de vino Barolo y puré fino de apionabo. Sabor profundo y redondo, equilibrado por el dulzor sutil de la raíz.']},
 {course:3,price:16,en:['Vanilla panna cotta','Cream gently infused with vanilla and softly set, served with raspberry coulis. Cool and supple, with a fragrant creaminess lifted by the fruit’s tartness.'],fr:['Panna cotta à la vanille','Crème délicatement infusée à la vanille et prise tout en souplesse, servie avec un coulis de framboise. Fraîche et fondante, sa douceur parfumée est relevée par l’acidité du fruit.'],es:['Panna cotta de vainilla','Nata suavemente infusionada con vainilla y cuajada con una textura delicada, servida con coulis de frambuesa. Fresca y suave, con una cremosidad aromática realzada por la acidez de la fruta.']},
 {course:3,price:18,en:['Espresso tiramisù','Espresso-soaked savoiardi layered with mascarpone cream and dusted with cocoa. Airy and generous, balancing the bitterness of coffee with a soft, creamy sweetness.'],fr:['Tiramisù à l’espresso','Biscuits savoiardi imbibés d’espresso, alternés avec une crème au mascarpone et poudrés de cacao. Aérien et généreux, entre amertume du café et douceur crémeuse.'],es:['Tiramisú al espresso','Bizcochos savoiardi empapados en espresso, en capas con crema de mascarpone y espolvoreados con cacao. Ligero y generoso, equilibra el amargor del café con una dulzura suave y cremosa.']}
];
